#需要替换intanceid 实例的具体名字
#需要替换testtest etcd管理员的密码

apiVersion: v1
kind: Service
metadata:
  name: sb-etcd-test-etcd
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    servicebroker: etcd-test-etcd

---

#Route to client
apiVersion: v1
kind: Route
metadata:
  name: sb-etcd-test-etcd
spec:
  host: sb-etcd-test-etcd.hhh.app.dataos.io
  port:
    targetPort: etcd-client-port
  to:
    kind: Service
    name: sb-etcd-test-etcd

---



apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-etcd-test-etcd1
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: etcd-test-etcd1
  template:
    metadata:
      labels:
        servicebroker_etcd_node: etcd-test-etcd1
        servicebroker: etcd-test-etcd
    spec:
      containers:
      - command:
        - /bin/sh 
        - /usr/bin/etcd-join.sh
        - http://sb-etcd-test-etcd.hhh.app.dataos.io:80
        - etcd1
        - http://sb-etcd-test-etcd1:2380
        - sb-etcd-test-etcd
        - testtest
        image: 172.30.188.59:5000/etcd---cjh/core-etcd-cluster
        imagePullPolicy: Always
        name: etcd1
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/bin/cluster_status.sh
            - testtest
            - http://sb-etcd-test-etcd0:2380
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-etcd-test-etcd1
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: etcd-test-etcd1

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-etcd-test-etcd2
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: etcd-test-etcd2
  template:
    metadata:
      labels:
        servicebroker_etcd_node: etcd-test-etcd2
        servicebroker: etcd-test-etcd
    spec:
      containers:
      - command:
        - /bin/sh 
        - /usr/bin/etcd-join.sh
        - http://sb-etcd-test-etcd.hhh.app.dataos.io:80
        - etcd2
        - http://sb-etcd-test-etcd2:2380
        - sb-etcd-test-etcd
        - testtest
        image: 172.30.188.59:5000/etcd---cjh/core-etcd-cluster
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/bin/cluster_status.sh
            - testtest
            - http://sb-etcd-test-etcd0:2380
        name: etcd3
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-etcd-test-etcd2
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: etcd-test-etcd2

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-etcd-test-etcd3
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: etcd-test-etcd3
  template:
    metadata:
      labels:
        servicebroker_etcd_node: etcd-test-etcd3
        servicebroker: etcd-test-etcd
    spec:
      containers:
      - command:
        - /bin/sh 
        - /usr/bin/etcd-join.sh
        - http://sb-etcd-test-etcd.hhh.app.dataos.io:80
        - etcd3
        - http://sb-etcd-test-etcd3:2380
        - sb-etcd-test-etcd
        - testtest
        image: 172.30.188.59:5000/etcd---cjh/core-etcd-cluster
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/bin/cluster_status.sh
            - testtest
            - http://sb-etcd-test-etcd0:2380
        imagePullPolicy: Always
        name: etcd3
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-etcd-test-etcd3
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: etcd-test-etcd3
